import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
 
import { cn } from "@/lib/utils";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";

import "quill/dist/quill.snow.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const materialIcons = localFont({
  src: "./material-icons.woff2",
  style: "normal",
  display: "swap",
  variable: "--font-material-icons",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Контролює поведінку віртуальної клавіатури
  // "resizes-visual" - клавіатура зменшує viewport (posune контент вгору)
  // "resizes-content" - клавіатура змінює розмір контенту
  // "overlays-content" - клавіатура накладається поверх контенту (за замовчуванням)
  interactiveWidget: "overlays-content",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          materialIcons.variable,
          "flex antialiased min-h-svh bg-background max-md:flex-col"
        )}
      >
        <Providers>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
