from .workspaces import CREATE_TABLE_WORKSPACES
from .projects import CREATE_TABLE_PROJECTS, CREATE_TABLE_PROJECTS_MEMBERS
from .tasks import CREATE_TABLE_TASKS
from .users import CREATE_TABLE_USERS
from .task_statuses import CREATE_TABLE_TASK_STATUSES
from .task_status_relations import CREATE_TABLE_TASK_STATUS_RELATIONS

SCHEMAS = {
    "CREATE_TABLE_USERS": CREATE_TABLE_USERS,
    "CREATE_TABLE_WORKSPACES": CREATE_TABLE_WORKSPACES,
    "CREATE_TABLE_PROJECTS": CREATE_TABLE_PROJECTS,
    "CREATE_TABLE_PROJECTS_MEMBERS": CREATE_TABLE_PROJECTS_MEMBERS,
    "CREATE_TABLE_TASKS": CREATE_TABLE_TASKS,
    "CREATE_TABLE_TASK_STATUSES": CREATE_TABLE_TASK_STATUSES,
    "CREATE_TABLE_TASK_STATUS_RELATIONS": CREATE_TABLE_TASK_STATUS_RELATIONS,
}

__all__ = ["SCHEMAS"]